! $Header: /mn/hox/ozon/ctm2_model/ctm2_src/dst_dst/dstscv.F90,v 1.1 2003/04/15 14:41:36 alfgr Exp $

! Purpose: Wet scavenging processes, development edition

! dstscv.F90 is based on, and is intended to one day replace, dstdpswet.F90
! dstscv.F90 implements wet deposition with size-dependent scavenging physics

! Usage:
! use dstscv ! [mdl] Aerosol scavenging properties

! Requires dst.h for ???
!#include <dst.h> /* Dust preprocessor tokens */

module dstscv ! [mdl] Aerosol scavenging properties
  use dead_precision ! [mdl] Precision r8, i8, ...
  use dstgrd,only:dst_nbr ! [mdl] Dust grid sizes
  implicit none
  save ! [stt] Changes to common variables are sticky
  
  ! Variables computed at run time, initialized in dst_psd_ini()
  real(r8) scv_cff_mss_avg_pcp_nrm_cnv(dst_nbr) ! [m2 kg-1] Mass mean scavenging coefficient, precipitation-normalized, convective
  real(r8) scv_cff_mss_avg_pcp_nrm_str(dst_nbr) ! [m2 kg-1] Mass mean scavenging coefficient, precipitation-normalized, stratiform
  real(r8) frc_ice_scv(dst_nbr) ! [frc] Fraction of ice cloud allowing nucleation scavenging
  real(r8) z_scv(dst_nbr) ! [(kg dust/kg rain)/(kg dust/kg air)] Scavenging ratio
  
contains
  
  subroutine dst_scv_cmn_ini()
    ! Purpose: Initialize wet scavenging parameters
    ! dst_scv_cmn_ini() is called by dst_msc_cmn_ini()
    ! Dependencies: Routine requires dmt_vwr, must be called after dst_psd_ini()
    use dstaer ! [mdl] Aerosol microphysical properties
    use dstgrd,only:dst_nbr ! [mdl] Dust grid sizes
    use vec_mdl,only:ntp_vec ! [mdl] Vector manipulation, interpolation, rebinning
    use xtr_mdl ! [mdl] Extrapolation constants
    implicit none
    ! Parameters
    integer,parameter::xtr_typ_LHS=xtr_vrb ! [enm] LHS Extrapolation type
    integer,parameter::xtr_typ_RHS=xtr_vrb ! [enm] RHS Extrapolation type
    ! Data generated by mie on Mon Aug 28 16:44:17 2000
    ! mie version Unknown dated Unknown
    ! Saharan dust aerosol mass extinction coefficient in m2 kg-1
    ! Saharan dust aerosol scavenging coefficient, precipitation-normalized in m2 kg-1
#if 0 /* Some Fortran compilers choke on very long comments */
    ! Command line: mie --no_wrn_ntp -no_mie --hrz --dbg=1 --dst_lbl=01 --dsd_mnm=1.0 --dsd_mxm=4000.0 --dsd_nbr=200 --gsd_pcp_anl=1.86 --dmt_pcp_nma=1000.0 --flx_vlm_pcp=1.0e-6 --aer_typ=saharan_dust --dist=lognormal --sz_grd=log --sz_mnm=0.005 --sz_mxm=50.0 --sz_nbr=64 --rds_nma=0.2986 --gsd_anl=2.0 /data/zender/mie/out.nc
#endif /* not 0 */
    integer,parameter::dst_nbr_hrz=64 ! [nbr] Number of high resolution bins
    real(r8),dimension(dst_nbr_hrz),parameter::scv_cff_pcp_nrm_cnv_dst_hrz=(/  &
         1.5897641e-03, 1.3476803e-03, 1.1436866e-03, 9.7166962e-04,  &
         8.2651991e-04, 7.0396246e-04, 6.0041808e-04, 5.1288848e-04,  &
         4.3885942e-04, 3.7622152e-04, 3.2320418e-04, 2.7831987e-04,  &
         2.4031854e-04, 2.0814942e-04, 1.8092897e-04, 1.5791466e-04,  &
         1.3848314e-04, 1.2211206e-04, 1.0836589e-04, 9.6884069e-05,  &
         8.7372275e-05, 7.9595913e-05, 7.3375915e-05, 6.8586836e-05,  &
         6.5157270e-05, 6.3072272e-05, 6.2379047e-05, 6.3195432e-05,  &
         6.5722859e-05, 7.0264716e-05, 7.7251738e-05, 8.7277396e-05,  &
         1.0114563e-04, 1.1993577e-04, 1.4508948e-04, 1.7852767e-04,  &
         6.9217011e-04, 9.8793171e-03, 3.1971984e-02, 6.2812500e-02,  &
         9.9596232e-02, 1.3957511e-01, 1.8010621e-01, 2.1895881e-01,  &
         2.5454021e-01, 2.8595984e-01, 3.1295082e-01, 3.3571437e-01,  &
         3.5475212e-01, 3.7072664e-01, 3.8436484e-01, 3.9640611e-01,  &
         4.0758434e-01, 4.1863608e-01, 4.3032637e-01, 4.4358557e-01,  &
         4.5924133e-01, 4.7840023e-01, 5.0210440e-01, 5.3104508e-01,  &
         5.6500381e-01, 6.0031271e-01, 6.2540495e-01, 6.4466858e-01 /)
    
    ! Stratiform scavenging
#if 0 /* Some Fortran compilers choke on very long comments */
    ! Command line: mie --no_wrn_ntp -no_mie --hrz --dbg=1 --dst_lbl=01 --dsd_mnm=1.0 --dsd_mxm=4000.0 --dsd_nbr=200 --gsd_pcp_anl=1.86 --dmt_pcp_nma=400.0 --flx_vlm_pcp=0.277e-6 --aer_typ=saharan_dust --dist=lognormal --sz_grd=log --sz_mnm=0.005 --sz_mxm=50.0 --sz_nbr=64 --rds_nma=0.2986 --gsd_anl=2.0 /data/zender/mie/out.nc
#endif /* not 0 */
    real(r8),dimension(dst_nbr_hrz),parameter::scv_cff_pcp_nrm_str_dst_hrz=(/  &
         4.9361251e-03, 4.1806730e-03, 3.5449979e-03, 3.0096555e-03,  &
         2.5584465e-03, 2.1778606e-03, 1.8566155e-03, 1.5852820e-03,  &
         1.3559718e-03, 1.1620797e-03, 9.9807011e-04, 8.5930259e-04,  &
         7.4188155e-04, 6.4253848e-04, 5.5852794e-04, 4.8754705e-04,  &
         4.2766484e-04, 3.7726737e-04, 3.3501090e-04, 2.9978782e-04,  &
         2.7069784e-04, 2.4702997e-04, 2.2824891e-04, 2.1399201e-04,  &
         2.0407054e-04, 1.9848152e-04, 1.9742698e-04, 2.0134579e-04,  &
         2.1095932e-04, 2.2733609e-04, 2.5198181e-04, 2.8696252e-04,  &
         3.3507260e-04, 4.0006099e-04, 4.8693677e-04, 6.0237874e-04,  &
         1.6499147e-03, 2.0755932e-02, 6.3879907e-02, 1.2215281e-01,  &
         1.8957390e-01, 2.6075196e-01, 3.3104798e-01, 3.9697531e-01,  &
         4.5638159e-01, 5.0836754e-01, 5.5303204e-01, 5.9116012e-01,  &
         6.2395012e-01, 6.5281636e-01, 6.7928034e-01, 7.0493299e-01,  &
         7.3145419e-01, 7.6064801e-01, 7.9442638e-01, 8.3490026e-01,  &
         8.8266754e-01, 9.3715608e-01, 9.9514586e-01, 1.0515112e+00,  &
         1.1009588e+00, 1.1354960e+00, 1.1283506e+00, 1.1151069e+00 /)
    
    real(r8),dimension(dst_nbr_hrz),parameter::dmt_ctr_hrz=(/  &
         1.0773910e-08, 1.2441516e-08, 1.4367239e-08, 1.6591027e-08,  &
         1.9159019e-08, 2.2124489e-08, 2.5548960e-08, 2.9503479e-08,  &
         3.4070084e-08, 3.9343519e-08, 4.5433190e-08, 5.2465424e-08,  &
         6.0586132e-08, 6.9963768e-08, 8.0792901e-08, 9.3298183e-08,  &
         1.0773906e-07, 1.2441511e-07, 1.4367232e-07, 1.6591021e-07,  &
         1.9159012e-07, 2.2124479e-07, 2.5548951e-07, 2.9503465e-07,  &
         3.4070069e-07, 3.9343499e-07, 4.5433163e-07, 5.2465396e-07,  &
         6.0586092e-07, 6.9963721e-07, 8.0792842e-07, 9.3298115e-07,  &
         1.0773897e-06, 1.2441503e-06, 1.4367223e-06, 1.6591009e-06,  &
         1.9158997e-06, 2.2124464e-06, 2.5548932e-06, 2.9503444e-06,  &
         3.4070044e-06, 3.9343472e-06, 4.5433130e-06, 5.2465357e-06,  &
         6.0586044e-06, 6.9963671e-06, 8.0792788e-06, 9.3298058e-06,  &
         1.0773891e-05, 1.2441495e-05, 1.4367213e-05, 1.6590999e-05,  &
         1.9158986e-05, 2.2124450e-05, 2.5548916e-05, 2.9503426e-05,  &
         3.4070024e-05, 3.9343449e-05, 4.5433106e-05, 5.2465330e-05,  &
         6.0586011e-05, 6.9963629e-05, 8.0792743e-05, 9.3298113e-05 /)
    
    ! Precomputed values for common configurations
#if 0
    ncks -H -u -C -F -v scv_cff_mss_avg_pcp_nrm ${DATA}/dst/mie/aer_saharan_dust_01_086.nc
    ncks -H -u -C -F -v scv_cff_mss_avg_pcp_nrm ${DATA}/dst/mie/aer_saharan_dust_02_086.nc
    ncks -H -u -C -F -v scv_cff_mss_avg_pcp_nrm ${DATA}/dst/mie/aer_saharan_dust_03_086.nc
    ncks -H -u -C -F -v scv_cff_mss_avg_pcp_nrm ${DATA}/dst/mie/aer_saharan_dust_04_086.nc
#endif /* not 0 */
    ! fxm: hb increased first to size bins to improve transport
    real(r8),dimension(4),parameter::scv_cff_mss_nrm_cnv_dst_04bn=(/ 0.02,0.05,0.104947,0.267706 /) ! [m2 kg-1] Mass mean scavenging coefficient, precipitation-normalized, convective
    real(r8),dimension(4),parameter::scv_cff_mss_nrm_str_dst_04bn=(/ 0.03,0.1,0.197463,0.478069 /) ! [m2 kg-1] Mass mean scavenging coefficient, precipitation-normalized, stratiform
    !    real(r8),dimension(4),parameter::scv_cff_mss_nrm_cnv_dst_04bn=(/ 7.60833e-05,0.00408381,0.104947,0.267706 /) ! [m2 kg-1] Mass mean scavenging coefficient, precipitation-normalized, convective
    !    real(r8),dimension(4),parameter::scv_cff_mss_nrm_str_dst_04bn=(/ 0.000247209,0.00852661,0.197463,0.478069 /) ! [m2 kg-1] Mass mean scavenging coefficient, precipitation-normalized, stratiform
    ! Input
    ! Output
    ! Input/Output
    ! Local
    integer sz_idx            ! [idx] Counting index 
    ! Main code
    
    ! Scavenging ratios
    ! fxm: z_scv is only used in old wet deposition scheme, remove once PJR/MKB scheme fully adopted
    do sz_idx=1,dst_nbr
!       z_scv(sz_idx)=200.0_r8       ! [(kg dust/kg rain)/(kg dust/kg air)] Duce Atlantic DLM91, Prospero everywhere Pro96b. p. 37
       z_scv(sz_idx)=750.0_r8         ! [(kg dust/kg rain)/(kg dust/kg air)] Tegen everywhere TeF94 p. 22901
!       z_scv(1)=1000.0_r8           ! [(kg dust/kg rain)/(kg dust/kg air)] Uematsu (except N. Atl. Pro96b. p. 37
    end do                    ! end loop over cst
    
    ! Sanity check
    if(dmt_vwr(1) < 0.0001e-6_r8.or.dmt_vwr(1) > 100.0e-6_r8)  &
         stop 'ERROR: dst_scv_cmn_ini() probably called before dst_psd_ini()'
    ! Initialize common block used for wet deposition
    do sz_idx=1,dst_nbr
       ! frc_ice_scv = 1.0_r8 for nucleation scavenging exactly as efficient per unit mass in ice as in liquid
       ! frc_ice_scv = 0.0_r8 if nucleation scavenging does not occur in ice
       frc_ice_scv(sz_idx)=1.0_r8 ! [frc] Fraction of ice cloud allowing nucleation scavenging
    end do                     ! end loop over cst
    call ntp_vec(dst_nbr_hrz,dmt_ctr_hrz,scv_cff_pcp_nrm_cnv_dst_hrz, &
         dst_nbr,dmt_vwr,scv_cff_mss_avg_pcp_nrm_cnv, &
         xtr_typ_LHS,xtr_typ_RHS)
    call ntp_vec(dst_nbr_hrz,dmt_ctr_hrz,scv_cff_pcp_nrm_str_dst_hrz, &
         dst_nbr,dmt_vwr,scv_cff_mss_avg_pcp_nrm_str, &
         xtr_typ_LHS,xtr_typ_RHS)
    ! Override automatic grid with preset grid if available
    if (dst_nbr == 4) then
       do sz_idx=1,dst_nbr             
          scv_cff_mss_avg_pcp_nrm_cnv(sz_idx)=scv_cff_mss_nrm_cnv_dst_04bn(sz_idx) ! [m2 kg-1] Mass mean scavenging coefficient, precipitation-normalized, convective
          scv_cff_mss_avg_pcp_nrm_str(sz_idx)=scv_cff_mss_nrm_str_dst_04bn(sz_idx) ! [m2 kg-1] Mass mean scavenging coefficient, precipitation-normalized, stratiform
       end do                 ! end loop over cst
    endif                     ! endif dst_nbr == 4
    
    write (6,'(a)') 'Scavenging coefficient information:'
    write (6,'(a3,3(a10,1x))') 'idx','dmt_vwr','scv_cnv','scv_str'
    write (6,'(a3,3(a10,1x))') '','um','m2 kg-1','m2 kg-1'
    do sz_idx=1,dst_nbr
       write (6,'(i3,3(es10.3,1x))') sz_idx, &
            dmt_vwr(sz_idx)*1.0e6_r8,scv_cff_mss_avg_pcp_nrm_cnv(sz_idx),scv_cff_mss_avg_pcp_nrm_str(sz_idx)
    end do                     ! end loop over cst
    
    return
  end subroutine dst_scv_cmn_ini                       ! end dst_scv_cmn_ini()
  
  
  
  subroutine clc_fsh_get( &
       dmt_aer,             & ! I 
       dns_aer,             & ! I
       clc_fsh)             ! O
    ! Purpose: Compute factor which corrects Stokes settling velocity to actual
    ! settling velocity when Reynolds' number is greater than 0.1
    ! clc_fsh_get() is called by dst_psd_ini()
    ! This implementation isolates the size-dependent sensitivity of the settling velocity 
    use dstgrd ! [mdl] Dust grid sizes
    use dstcst ! [mdl] Physical constants for dust routines
    implicit none
    ! Parameters
    ! Apparently Boltzmann's constant is not set anywhere by CCM or MATCH
    real(r8),parameter::cst_Boltzmann=1.38063e-23 ! [J K-1] Boltzmann's constant
    real(r8),parameter::prs_mdp=100000.0 ! [Pa] Pressure 
    real(r8),parameter::tpt_mdp=295.0 ! [K] Temperature
    real(r8),parameter::tpt_vrt=295.0 ! [K] Virtual temperature
    ! Input
    real(r8) dmt_aer(dst_nbr)     ! [m] Particle diameter
    real(r8) dns_aer(dst_nbr)     ! [kg m-3] Particle density
    ! Output
    real(r8) clc_fsh(dst_nbr)     ! [frc] Correction to Stokes settling velocity
    ! Local
    real(r8) pi       ! [frc] 3
    integer itr_idx           ! [idx] Counting index
    integer m                 ! [idx] Counting index
    real(r8) cff_drg_grv(dst_nbr) ! [frc] Drag coefficient at terminal velocity
    real(r8) dns_mdp              ! [kg m-3] Midlayer density
    real(r8) eps_crr              ! [frc] Current relative accuracy
    real(r8) eps_max              ! [frc] Relative accuracy for convergence
    real(r8) mfp_atm              ! [m] Mean free path of air
    real(r8) ryn_nbr_grv(dst_nbr) ! [frc] Reynolds number at terminal velocity
    real(r8) slp_crc(dst_nbr)     ! [frc] Slip correction factor
    real(r8) vlc_grv(dst_nbr)     ! [m s-1] Settling velocity
    real(r8) vlc_grv_old          ! [m s-1] Previous gravitational settling velocity
    real(r8) vlc_stk(dst_nbr)     ! [m s-1] Stokes settling velocity
    real(r8) vsc_dyn_atm          ! [kg m-1 s-1] Dynamic viscosity of air
    real(r8) vsc_knm_atm          ! [m2 s-1] Kinematic viscosity of atmosphere 
    ! Initialize some variables
    pi=4.0_DBLKIND*atan(1.0_DBLKIND)        ! [frc] 3
    eps_max=1.0e-4_r8            ! [frc] Relative accuracy for convergence
    dns_mdp=prs_mdp/(tpt_vrt*gas_cst_dry_air) ! [kg m-3]
    ! Size-independent thermokinetic properties
    vsc_dyn_atm=1.72e-5_r8*((tpt_mdp/273.0_r8)**1.5_r8)*393.0_r8/(tpt_mdp+120.0_r8) ! [kg m-1 s-1] RoY94  p. 102
    mfp_atm=2.0_r8*vsc_dyn_atm/(prs_mdp*sqrt(8.0_r8*mmw_dry_air/(pi*gas_cst_unv*tpt_mdp))) ! [m] Mean free path of air SeP97 p. 455
    vsc_knm_atm=vsc_dyn_atm/dns_mdp ! [m2 s-1] Kinematic viscosity of air
    
    do m=1,dst_nbr
       slp_crc(m)=1.0_r8+2.0_r8*mfp_atm*(1.257_r8+0.4_r8*exp(-1.1_r8*dmt_aer(m)/(2.0*mfp_atm)))/dmt_aer(m) ! [frc] Slip correction factor SeP97 p. 464
       vlc_stk(m)=(1.0_r8/18.0_r8)*dmt_aer(m)*dmt_aer(m)*dns_aer(m)*grv_sfc*slp_crc(m)/vsc_dyn_atm ! [m s-1] Stokes settling velocity SeP97 p. 466
    end do                     ! end loop over size
    
    ! For Reynolds number flows Re < 0.1 Stokes' velocity is valid for vlc_grv SeP97 p. 466 (8.42)
    ! For larger Re, inertial effects become important and empirical drag coefficients must be employed
    ! Implicit equation for Re, Cd, and Vt is SeP97 p. 467 (8.44)
    ! Using Stokes' velocity rather than iterative solution with empirical drag coefficient causes 60% errors for D = 200 um SeP97 p. 468
    
    ! Iterative solution for drag coefficient, Reynolds number, and terminal velocity
    do m=1,dst_nbr
       ! Initialize accuracy and counter
       eps_crr=eps_max+1.0_r8    ! [frc] Current relative accuracy
       itr_idx=0              ! [idx] Counting index
       ! Initial guess for vlc_grv is exact for Re < 0.1
       vlc_grv(m)=vlc_stk(m)  ! [m s-1]
       do while(eps_crr > eps_max)
          ! Save terminal velocity for convergence test
          vlc_grv_old=vlc_grv(m) ! [m s-1] 
          ryn_nbr_grv(m)=vlc_grv(m)*dmt_aer(m)/vsc_knm_atm ! [frc] SeP97 p. 460
          ! Update drag coefficient based on new Reynolds number
          if (ryn_nbr_grv(m) < 0.1_r8) then
             cff_drg_grv(m)=24.0_r8/ryn_nbr_grv(m) ! Stokes' law Sep97 p. 463 (8.32)
          else if (ryn_nbr_grv(m) < 2.0_r8) then
             cff_drg_grv(m)=(24.0_r8/ryn_nbr_grv(m))* &
                  (1.0_r8+3.0_r8*ryn_nbr_grv(m)/16.0_r8+9.0_r8*ryn_nbr_grv(m)*ryn_nbr_grv(m)*log(2.0_r8*ryn_nbr_grv(m))/160.0_r8) ! Sep97 p. 463 (8.32)
          else if (ryn_nbr_grv(m) < 500.0_r8) then
             cff_drg_grv(m)=(24.0_r8/ryn_nbr_grv(m))*(1.0_r8+0.15_r8*ryn_nbr_grv(m)**0.687_r8) ! Sep97 p. 463 (8.32)
          else if (ryn_nbr_grv(m) < 2.0e5_r8) then
             cff_drg_grv(m)=0.44_r8 ! Sep97 p. 463 (8.32)
          else
             stop 'Reynolds number too large in clc_fsh_get()'
          endif               ! end else
          ! Update terminal velocity based on new Reynolds number and drag coefficient
          vlc_grv(m)=sqrt(4.0_r8*grv_sfc*dmt_aer(m)*slp_crc(m)*dns_aer(m)/(3.0_r8*cff_drg_grv(m)*dns_mdp)) ! [m s-1] Terminal velocity SeP97 p. 467 (8.44)
          eps_crr=abs((vlc_grv(m)-vlc_grv_old)/vlc_grv(m)) ! Relative convergence
          if (itr_idx == 12) then
             ! Numerical pingpong may occur when Re = 0.1, 2.0, or 500.0 due to discontinuities in derivative of drag coefficient
             vlc_grv(m)=0.5_r8*(vlc_grv(m)+vlc_grv_old) ! [m s-1]
          endif               ! endif
          if (itr_idx > 20) then
             write (6,'(a)') 'dst: Terminal velocity not converging in clc_fsh_get(), breaking loop...'
             goto 100         ! Jump to next iteration
          endif               ! endif
          itr_idx=itr_idx+1
       end do                 ! end while
100    continue               ! Label to jump to when iteration does not converge
    end do                     ! end loop over size
    
    ! Compute factors to convert Stokes' settling velocities to actual settling velocities
    do m=1,dst_nbr
       clc_fsh(m)=vlc_grv(m)/vlc_stk(m) ! [frc] Correction to Stokes settling velocity
    end do                     ! end loop over size
    return
  end subroutine clc_fsh_get                       ! end clc_fsh_get()
  
end module dstscv
