! $Header: /mn/hox/ozon/ctm2_model/ctm2_src/dst_dst/dstodx.F90,v 1.1 2003/04/15 14:41:36 alfgr Exp $

! Purpose: Information needed to compute optical depth
! These variables are initialized in dst_odx_cmn_ini() which is called by dst_msc_cmn_ini() 

! Usage:
! use dstodx ! [mdl] Optical depth information

module dstodx ! [mdl Optical depth information
  use dstgrd,only:dst_nbr ! [mdl] Dust grid sizes
  use precision ! [mdl] Precision r8, i8, ...
  implicit none
  save ! [stt] Changes to common variables are sticky
  
  ! Optical depth info initialized in dst_odx_cmn_ini()
  real(r8) ext_cff_mss_dst_dgn(dst_nbr) ! [m2 kg-1] Mass extinction coefficient of dust for diagnostic optical depth
  real(r8) bck_cff_mss_dst_dgn(dst_nbr) ! [m2 kg-1] Mass backscatter coefficient of dust for diagnostic LIDAR backscatter
  
  contains
    
    subroutine dst_odx_cmn_ini()
      ! Purpose: Initialize optical depth module
      ! dst_odx_cmn_ini() is called by dst_msc_cmn_ini()
      ! Dependencies: Routine requires dmt_swr, must be called after dst_psd_ini()
      ! NB: Nomenclature encodes wavelength in microns as last three digits
      ! Thus ..._063 means "evaluated at 0.63 microns" (AVHRR Channel 1)
      ! Thus ..._050 means "evaluated at 0.50 microns" (WMO std wavelength)
      use dstgrd,only:dst_nbr ! [mdl] Dust grid sizes
      use dstpsd,only:dmt_swr ! [mdl] Dust particle size distributions
      use precision ! [mdl] Precision r8, i8, ...
      use vec_mdl,only:ntp_vec ! [mdl] Vector manipulation, interpolation, rebinning
      use xtr_mdl ! [mdl] Extrapolation constants
      implicit none
      ! Parameters
      integer,parameter::xtr_typ_LHS=xtr_vrb ! [enm] LHS Extrapolation type
      integer,parameter::xtr_typ_RHS=xtr_vrb ! [enm] RHS Extrapolation type
      ! High resolution specific extinction
      ! Data generated by mie on Sun May 21 12:39:02 2000
      ! mie version Unknown dated Unknown
      ! Saharan dust aerosol mass extinction coefficient in m2 kg-1
#if 0 /* Some Fortran compilers choke on very long comments */
      ! Command line: mie --no_wrn_ntp --hrz --dbg=1 --dst_lbl=01 --aer_typ=saharan_dust --dist=lognormal --wvl_grd=reg --wvl_nbr=1 --wvl_mnm=0.625 --wvl_mxm=0.635 --bnd_nbr=2 --sz_grd=log --sz_mnm=0.005 --sz_mxm=50.0 --sz_nbr=64 --rds_nma=0.2986 --gsd_anl=2.0 /data/zender/dst/mie/aer_saharan_dust_hrz_063.nc
#endif /* not 0 */
      integer,parameter::dst_nbr_hrz=64 ! [nbr] Number of high resolution bins
      real(r8),dimension(dst_nbr_hrz),parameter::ext_cff_mss_dst_hrz=(/  &
           2.0708963e+01, 2.0787266e+01, 2.0905321e+01, 2.1083765e+01,  &
           2.1354128e+01, 2.1764294e+01, 2.2388514e+01, 2.3339769e+01,  &
           2.4791828e+01, 2.7011854e+01, 3.0411173e+01, 3.5623936e+01,  &
           4.3629124e+01, 5.5939003e+01, 7.4890823e+01, 1.0408587e+02,  &
           1.4903189e+02, 2.1799266e+02, 3.2283185e+02, 4.7891080e+02,  &
           7.0142871e+02, 9.9449951e+02, 1.3420798e+03, 1.7650575e+03,  &
           2.4588586e+03, 3.1149944e+03, 3.1692219e+03, 3.7535420e+03,  &
           3.4849006e+03, 3.5819019e+03, 2.9263354e+03, 2.1190962e+03,  &
           1.3966730e+03, 8.7480927e+02, 7.7586859e+02, 8.3421100e+02,  &
           8.8776550e+02, 6.5199640e+02, 4.4449576e+02, 5.0862491e+02,  &
           3.6941647e+02, 3.4139664e+02, 2.5660623e+02, 2.5565089e+02,  &
           1.9882104e+02, 1.7131413e+02, 1.5897310e+02, 1.3040485e+02,  &
           1.0873315e+02, 9.4183754e+01, 8.2329193e+01, 7.0274239e+01,  &
           6.2494713e+01, 5.3757774e+01, 4.6389805e+01, 3.9296574e+01,  &
           3.4052509e+01, 2.9806177e+01, 2.5394520e+01, 2.2001064e+01,  &
           1.9136105e+01, 1.6531433e+01, 1.4268397e+01, 1.2337605e+01 /)
      
      real(r8),dimension(dst_nbr_hrz),parameter::bck_cff_mss_dst_hrz=(/ &
           1.8287706e-01, 2.8151751e-01, 4.3331161e-01, 6.6684699e-01, &
           1.0260307e+00, 1.5782344e+00, 2.4267094e+00, 3.7294347e+00, &
           5.7275743e+00, 8.7881527e+00, 1.3467331e+01, 2.0602795e+01, &
           3.1445412e+01, 4.7839127e+01, 7.2449333e+01, 1.0900669e+02, &
           1.6244237e+02, 2.3854900e+02, 3.4221573e+02, 4.7203854e+02, &
           6.0739752e+02, 6.8641949e+02, 5.9851849e+02, 2.8812747e+02, &
           9.2606895e+01, 5.1528619e+02, 7.0644330e+02, 2.7017950e+02, &
           7.9771112e+02, 5.8021039e+02, 1.5465198e+03, 8.3642798e+02, &
           1.2034253e+03, 2.0943264e+03, 3.9599839e+03, 1.1656747e+03, &
           2.0319851e+03, 1.9789921e+03, 4.4685922e+02, 4.3062268e+02, &
           3.2907074e+02, 2.3875323e+02, 7.0980408e+01, 7.1047722e+01, &
           8.2313484e+01, 1.6719696e+02, 2.0395456e+02, 1.2383693e+02, &
           5.0439064e+01, 8.2685661e+01, 8.4868599e+01, 1.3930923e+01, &
           3.5126511e+01, 2.8565975e+01, 9.2676735e+00, 2.0149477e+01, &
           1.7998220e+01, 1.4562830e+01, 5.7134051e+00, 3.0591731e+00, &
           1.3540574e+01, 9.7294378e+00, 7.2652726e+00, 7.4089174e+00 /)

      real(r8),dimension(dst_nbr_hrz),parameter::dmt_ctr_hrz=(/  &
           1.0773910e-08, 1.2441516e-08, 1.4367239e-08, 1.6591027e-08,  &
           1.9159019e-08, 2.2124489e-08, 2.5548960e-08, 2.9503479e-08,  &
           3.4070084e-08, 3.9343519e-08, 4.5433190e-08, 5.2465424e-08,  &
           6.0586132e-08, 6.9963768e-08, 8.0792901e-08, 9.3298183e-08,  &
           1.0773906e-07, 1.2441511e-07, 1.4367232e-07, 1.6591021e-07,  &
           1.9159012e-07, 2.2124479e-07, 2.5548951e-07, 2.9503465e-07,  &
           3.4070069e-07, 3.9343499e-07, 4.5433163e-07, 5.2465396e-07,  &
           6.0586092e-07, 6.9963721e-07, 8.0792842e-07, 9.3298115e-07,  &
           1.0773897e-06, 1.2441503e-06, 1.4367223e-06, 1.6591009e-06,  &
           1.9158997e-06, 2.2124464e-06, 2.5548932e-06, 2.9503444e-06,  &
           3.4070044e-06, 3.9343472e-06, 4.5433130e-06, 5.2465357e-06,  &
           6.0586044e-06, 6.9963671e-06, 8.0792788e-06, 9.3298058e-06,  &
           1.0773891e-05, 1.2441495e-05, 1.4367213e-05, 1.6590999e-05,  &
           1.9158986e-05, 2.2124450e-05, 2.5548916e-05, 2.9503426e-05,  &
           3.4070024e-05, 3.9343449e-05, 4.5433106e-05, 5.2465330e-05,  &
           6.0586011e-05, 6.9963629e-05, 8.0792743e-05, 9.3298113e-05 /)
      ! fxm: dmt_grd only needed for rbn_vec(), not ntp_vec()
      real(r8),dimension(dst_nbr_hrz+1),parameter::dmt_grd_hrz=(/  &
           9.9999999e-09, 1.1547820e-08, 1.3335214e-08, 1.5399264e-08,  &
           1.7782792e-08, 2.0535246e-08, 2.3713731e-08, 2.7384189e-08,  &
           3.1622768e-08, 3.6517402e-08, 4.2169638e-08, 4.8696737e-08,  &
           5.6234114e-08, 6.4938142e-08, 7.4989394e-08, 8.6596401e-08,  &
           9.9999959e-08, 1.1547814e-07, 1.3335207e-07, 1.5399257e-07,  &
           1.7782784e-07, 2.0535238e-07, 2.3713721e-07, 2.7384178e-07,  &
           3.1622753e-07, 3.6517383e-07, 4.2169614e-07, 4.8696711e-07,  &
           5.6234080e-07, 6.4938098e-07, 7.4989345e-07, 8.6596339e-07,  &
           9.9999886e-07, 1.1547806e-06, 1.3335199e-06, 1.5399247e-06,  &
           1.7782772e-06, 2.0535224e-06, 2.3713706e-06, 2.7384158e-06,  &
           3.1622731e-06, 3.6517358e-06, 4.2169586e-06, 4.8696675e-06,  &
           5.6234039e-06, 6.4938054e-06, 7.4989293e-06, 8.6596283e-06,  &
           9.9999825e-06, 1.1547799e-05, 1.3335190e-05, 1.5399237e-05,  &
           1.7782761e-05, 2.0535210e-05, 2.3713690e-05, 2.7384142e-05,  &
           3.1622712e-05, 3.6517336e-05, 4.2169562e-05, 4.8696649e-05,  &
           5.6234010e-05, 6.4938016e-05, 7.4989250e-05, 8.6596228e-05, &
           9.9999997e-05 /)
      
      ! Precomputed values for common configurations
      ! Data generated by ${HOME}/dst/psd.pl calling mie:
      ! ${HOME}/dst/psd.pl --dbg=1 --ODX --aer_nbr=4 --dst_lbl={01,02,03,04} --sz_mnm={0.05,0.5,1.25,2.5} --sz_mxm={0.5,1.25,2.5,5.0} --sz_nbr={200,25,25,25} --wvl_odx_mnm=0.625 --wvl_odx_mxm=0.635 > & ! ${DATA}/dst/mie/psd_ODX.txt
#if 0 /* Some Fortran compilers choke on very long comments */
      ! mie --no_wrn_ntp --dbg=1 --dst_lbl=01 --aer_typ=saharan_dust --dist=lognormal --wvl_grd=reg --wvl_nbr=1 --wvl_mnm=0.625 --wvl_mxm=0.635 --bnd_nbr=2 --sz_grd=log --sz_mnm=0.05 --sz_mxm=0.5 --sz_nbr=200 --rds_nma=0.2986 --gsd_anl=2.0 /data/zender/dst/mie/aer_saharan_dust_01_063.nc
#endif /* not 0 */
      real(r8),dimension(4),parameter::ext_cff_mss_dst_063_04bn=(/ 2892.77,835.046,382.509,196.051 /) ! [m2 kg-1] Mass extinction coefficient of dust for diagnostic optical depth
      real(r8),dimension(4),parameter::bck_cff_mss_dst_063_04bn=(/ 986.421,1824.84,238.787,133.724 /) ! [m2 kg-1] Mass backscatter coefficient of dust for diagnostic LIDAR backscatter
      ! Input
      ! Output
      ! Input/Output
      ! Local
      integer sz_idx            ! [idx] Counting index 
      ! Main code
      ! Sanity check
      if(dmt_swr(1) < 0.0001e-6_r8.or.dmt_swr(1) > 100.0e-6_r8)  &
           stop 'ERROR: dst_odx_cmn_ini() probably called before dst_psd_ini()'
      ! Initialize common block used for diagnostic optical depth output
      ! NB: dmt_swr is only variable that requires dstpsd.h in this routine
      call ntp_vec(dst_nbr_hrz,dmt_ctr_hrz,ext_cff_mss_dst_hrz,dst_nbr,dmt_swr,ext_cff_mss_dst_dgn,xtr_typ_LHS,xtr_typ_RHS)
      !  call rbn_vec(dst_nbr_hrz,dmt_grd_hrz,ext_cff_mss_dst_hrz, &
      !      dst_nbr,dmt_grd,ext_cff_mss_dst_dgn, &
      !      xtr_typ_LHS,xtr_typ_RHS)
      call ntp_vec(dst_nbr_hrz,dmt_ctr_hrz,bck_cff_mss_dst_hrz,dst_nbr,dmt_swr,bck_cff_mss_dst_dgn,xtr_typ_LHS,xtr_typ_RHS)
      
      ! Override automatic grid with preset grid if available
      if (dst_nbr == 4) then
         do sz_idx=1,dst_nbr             
            ext_cff_mss_dst_dgn(sz_idx)=ext_cff_mss_dst_063_04bn(sz_idx) ! [m2 kg-1] Mass extinction coefficient of dust for diagnostic optical depth
            bck_cff_mss_dst_dgn(sz_idx)=bck_cff_mss_dst_063_04bn(sz_idx) ! [m2 kg-1] Mass backscatter coefficient of dust for diagnostic LIDAR backscatter
         end do                 ! end loop over cst
      endif                     ! endif dst_nbr == 4
      
      write (6,'(a)') 'Optical depth information:'
      write (6,'(a3,3(a10,1x))') 'idx','dmt_swr','ext_spc','bck_spc'
      write (6,'(a3,3(a10,1x))') '','um','m2 kg-1','m2 kg-1'
      do sz_idx=1,dst_nbr
         write (6,'(i3,3(es10.3,1x))') sz_idx, &
              dmt_swr(sz_idx)*1.0e6_r8,ext_cff_mss_dst_dgn(sz_idx),bck_cff_mss_dst_dgn(sz_idx)
      end do                     ! end loop over cst
      
      return
    end subroutine dst_odx_cmn_ini                       ! end dst_odx_cmn_ini()
    
  end module dstodx
  
