! $Header: /mn/hox/ozon/ctm2_model/ctm2_src/dst_dst/dstrad.F90,v 1.1 2003/04/15 14:41:36 alfgr Exp $

! Purpose: Optical properties needed by dust parameterization
! dstrad is initialized on first use
! dstrad is first used in BXM:aer(), CCM:control/main()

! Usage:
! use dstrad ! [mdl] Dust radiative properties

! dst.h needed for DST_NBR
#include <dst.h> /* Dust preprocessor tokens */

module dstrad ! [mdl Dust radiative properties
  use dstgrd,only:bnd_nbr_LW,bnd_nbr_SW,bnd_nbr_GSFC_LW,dst_nbr ! [mdl] Dust grid sizes
  use precision ! [mdl] Precision r8, i8, ...
  implicit none
  save ! [stt] Changes to common variables are sticky
  
  ! Parameters
  integer,parameter,private::bnd_SW_sz_nbr=bnd_nbr_SW*dst_nbr ! [nbr] Number of elements in 2-D SW arrays
  integer,parameter,private::bnd_LW_sz_nbr=bnd_nbr_LW*dst_nbr ! [nbr] Number of elements in 2-D LW arrays
  
  ! Microphysical optical properties on CCM grid
  real(r8) abs_cff_mss_dst(bnd_nbr_LW,dst_nbr) ! [m2 kg-1] Mass absorption coefficient of dust
  real(r8) asm_prm_dst(bnd_nbr_SW,dst_nbr) ! [frc] Asymmetry parameter of dust
  real(r8) ext_cff_mss_dst(bnd_nbr_SW,dst_nbr) ! [m2 kg-1] Mass extinction coefficient of dust
  real(r8) ss_alb_dst(bnd_nbr_SW,dst_nbr) ! [frc] Single scattering albedo of dust
  
  ! Microphysical optical properties on GSFC grid
  real(r8) asm_prm_dst_GSFC_LW(bnd_nbr_GSFC_LW,dst_nbr) ! [frc] Asymmetry parameter of dust
  real(r8) ext_cff_mss_dst_GSFC_LW(bnd_nbr_GSFC_LW,dst_nbr) ! [m2 kg-1] Mass extinction coefficient of dust
  real(r8) ss_alb_dst_GSFC_LW(bnd_nbr_GSFC_LW,dst_nbr) ! [frc] Single scattering albedo of dust
  
  ! Local
  integer bnd_idx           ! [idx] Index over bnd dimension
  
#if DST_NBR != 4
  integer sz_idx            ! [idx] Index over sz dimension
  ! Default radiative properties when pre-computed initialization is unavailable
  data ((ext_cff_mss_dst(bnd_idx,sz_idx),bnd_idx=1,bnd_nbr_SW),sz_idx=1,dst_nbr) / bnd_SW_sz_nbr * 0.0 /
  data ((asm_prm_dst(bnd_idx,sz_idx),bnd_idx=1,bnd_nbr_SW),sz_idx=1,dst_nbr) / bnd_SW_sz_nbr * 0.0 /
  data ((ss_alb_dst(bnd_idx,sz_idx),bnd_idx=1,bnd_nbr_SW),sz_idx=1,dst_nbr) / bnd_SW_sz_nbr * 0.0 /
  data ((abs_cff_mss_dst(bnd_idx,sz_idx),bnd_idx=1,bnd_nbr_LW),sz_idx=1,dst_nbr) / bnd_LW_sz_nbr * 0.0 /
#endif /* DST_NBR > 4 */
#if DST_NBR == 4
  ! Data generated by mie on Thu Jun 22 10:27:07 2000
  ! mie version Unknown dated Unknown
  ! Saharan dust aerosol mass extinction/absorption coefficients in m2 kg-1
#if 0
  ! Command line: mie --no_wrn_ntp --dbg=1 --dst_lbl=01 --aer_typ=saharan_dust --dist=lognormal --bnd_nbr=20 --wvl_grd=CCM_SW --bnd_SW_LW=5e-06 --sz_grd=log --sz_mnm=0.05 --sz_mxm=0.5 --sz_nbr=200 --rds_nma=0.2986 --gsd_anl=2.0 /data/zender/dst/mie/aer_saharan_dust_01_CCM_SW.nc
#endif /* not 0 */
  data (ext_cff_mss_dst(bnd_idx,01),bnd_idx=1,bnd_nbr_SW) / &
       2.0330439e+03, 2.0891292e+03, 2.1200874e+03, 2.1412832e+03,  &
       2.1588303e+03, 2.1723618e+03, 2.1886194e+03, 2.6171516e+03,  &
       2.8603438e+03, 2.3851243e+03, 1.3806552e+03, 8.0256543e+02,  &
       4.2395282e+02, 2.1294937e+02, 1.0231668e+02, 3.1816683e+01,  &
       1.4103435e+02, 2.2511139e+01, 2.1238750e+01 /
  
  data (asm_prm_dst(bnd_idx,01),bnd_idx=1,bnd_nbr_SW) / &
       8.5012609e-01, 8.1487173e-01, 8.0047435e-01, 7.8767693e-01,  &
       7.7359664e-01, 7.5838971e-01, 7.1520561e-01, 6.6961879e-01,  &
       6.9672924e-01, 6.8454117e-01, 6.1410713e-01, 5.4495609e-01,  &
       4.3178445e-01, 2.7839592e-01, 1.6062993e-01, 9.3713574e-02,  &
       1.8981309e-01, 7.5941019e-02, 6.9214344e-02 /
  
  data (ss_alb_dst(bnd_idx,01),bnd_idx=1,bnd_nbr_SW) / &
       5.6546235e-01, 6.0831106e-01, 6.2899089e-01, 6.4785075e-01,  &
       6.6822410e-01, 6.8959159e-01, 7.4484694e-01, 9.3423676e-01,  &
       9.8157275e-01, 9.8394841e-01, 9.8020130e-01, 9.7384906e-01,  &
       9.6305627e-01, 9.1788888e-01, 6.4025444e-01, 7.3822856e-01,  &
       6.1584687e-01, 7.7208787e-01, 6.9280124e-01 /
  
  data (abs_cff_mss_dst(bnd_idx,01),bnd_idx=1,bnd_nbr_LW) / &
       6.2364349e+01, 8.7375420e+01, 5.8844006e+01, 9.2056694e+01,  &
       1.5903902e+02, 5.4979145e+01 /
  
  data (ext_cff_mss_dst_GSFC_LW(bnd_idx,01),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       2.9243296e+01, 5.2940281e+01, 5.8598167e+01, 7.1879066e+01,  &
       1.1848126e+02, 1.4937146e+02, 4.8476639e+01, 4.3719570e+01,  &
       2.5397701e+01, 7.5317413e+01 /
  
  data (asm_prm_dst_GSFC_LW(bnd_idx,01),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       1.9384337e-03, 4.8094061e-03, 7.5903446e-03, 1.3707597e-02,  &
       2.6967283e-02, 1.8978948e-02, 2.3501966e-02, 3.6907643e-02,  &
       7.0422746e-02, 5.0698835e-03 /
  
  data (ss_alb_dst_GSFC_LW(bnd_idx,01),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       7.2951126e-04, 2.9765684e-03, 3.9022856e-03, 1.3984219e-02,  &
       3.8414419e-02, 9.0388162e-03, 1.6342787e-02, 7.3009945e-02,  &
       5.7587028e-01, 1.9731023e-03 /
  
  ! Data generated by mie on Thu Jun 22 10:27:28 2000
  ! mie version Unknown dated Unknown
  ! Saharan dust aerosol mass extinction/absorption coefficients in m2 kg-1
#if 0
  ! Command line: mie --no_wrn_ntp --dbg=1 --dst_lbl=02 --aer_typ=saharan_dust --dist=lognormal --bnd_nbr=20 --wvl_grd=CCM_SW --bnd_SW_LW=5e-06 --sz_grd=log --sz_mnm=0.5 --sz_mxm=1.25 --sz_nbr=25 --rds_nma=0.2986 --gsd_anl=2.0 /data/zender/dst/mie/aer_saharan_dust_02_CCM_SW.nc
#endif /* not 0 */
  data (ext_cff_mss_dst(bnd_idx,02),bnd_idx=1,bnd_nbr_SW) / &
       7.8262830e+02, 7.8778107e+02, 7.8952216e+02, 7.9148956e+02,  &
       7.9427673e+02, 7.9764612e+02, 8.1291437e+02, 8.2675305e+02,  &
       8.6995483e+02, 1.0050466e+03, 1.2346045e+03, 1.2380098e+03,  &
       1.0699143e+03, 7.6386401e+02, 3.9692847e+02, 1.9117094e+02,  &
       4.7204376e+02, 1.5388454e+02, 1.3822670e+02 /
  
  data (asm_prm_dst(bnd_idx,02),bnd_idx=1,bnd_nbr_SW) / &
       9.3421656e-01, 9.2417568e-01, 9.1922462e-01, 9.1412079e-01,  &
       9.0820360e-01, 9.0107584e-01, 8.7844777e-01, 7.1817464e-01,  &
       6.3376713e-01, 6.3368660e-01, 6.7951250e-01, 6.9722050e-01,  &
       6.8857056e-01, 6.6047829e-01, 6.0414356e-01, 4.8596469e-01,  &
       6.4367348e-01, 4.3762487e-01, 4.0630528e-01 /
  
  data (ss_alb_dst(bnd_idx,02),bnd_idx=1,bnd_nbr_SW) / &
       5.2459216e-01, 5.3059661e-01, 5.3450143e-01, 5.4074711e-01,  &
       5.4943669e-01, 5.6137270e-01, 6.0587305e-01, 8.3562130e-01,  &
       9.3682617e-01, 9.5806843e-01, 9.7297680e-01, 9.7784382e-01,  &
       9.7830802e-01, 9.6504617e-01, 8.6852616e-01, 9.3751299e-01,  &
       8.4019893e-01, 9.5268613e-01, 9.3405902e-01 /
  
  data (abs_cff_mss_dst(bnd_idx,02),bnd_idx=1,bnd_nbr_LW) / &
       6.7039940e+01, 9.3054230e+01, 6.3752914e+01, 1.1043731e+02,  &
       2.1707288e+02, 6.1210907e+01 /
  
  data (ext_cff_mss_dst_GSFC_LW(bnd_idx,02),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       3.0467600e+01, 6.0059967e+01, 6.5194565e+01, 9.5690796e+01,  &
       2.5295988e+02, 1.7341553e+02, 5.9816128e+01, 8.1390846e+01,  &
       1.4571666e+02, 8.1157990e+01 /
  
  data (asm_prm_dst_GSFC_LW(bnd_idx,02),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       1.0977047e-02, 2.7142672e-02, 4.2983443e-02, 7.8423649e-02,  &
       1.5503588e-01, 1.1128971e-01, 1.3417719e-01, 2.1234663e-01,  &
       3.9536625e-01, 2.8675849e-02 /
  
  data (ss_alb_dst_GSFC_LW(bnd_idx,02),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       8.9800581e-03, 3.4551531e-02, 4.4868831e-02, 1.3669457e-01,  &
       2.6666442e-01, 9.1415502e-02, 1.4840369e-01, 4.1344982e-01,  &
       8.9602399e-01, 2.3356708e-02 /
  
  ! Data generated by mie on Thu Jun 22 10:27:44 2000
  ! mie version Unknown dated Unknown
  ! Saharan dust aerosol mass extinction/absorption coefficients in m2 kg-1
#if 0
  ! Command line: mie --no_wrn_ntp --dbg=1 --dst_lbl=03 --aer_typ=saharan_dust --dist=lognormal --bnd_nbr=20 --wvl_grd=CCM_SW --bnd_SW_LW=5e-06 --sz_grd=log --sz_mnm=1.25 --sz_mxm=2.5 --sz_nbr=25 --rds_nma=0.2986 --gsd_anl=2.0 /data/zender/dst/mie/aer_saharan_dust_03_CCM_SW.nc
#endif /* not 0 */
  data (ext_cff_mss_dst(bnd_idx,03),bnd_idx=1,bnd_nbr_SW) / &
       3.6075204e+02, 3.6331461e+02, 3.6409647e+02, 3.6441281e+02,  &
       3.6497607e+02, 3.6594357e+02, 3.6856805e+02, 3.8093378e+02,  &
       3.7893677e+02, 4.0725134e+02, 3.9028488e+02, 4.0814703e+02,  &
       5.0037268e+02, 6.0288885e+02, 5.6525159e+02, 4.3517175e+02,  &
       5.7911523e+02, 4.0223413e+02, 3.7889975e+02 /
  
  data (asm_prm_dst(bnd_idx,03),bnd_idx=1,bnd_nbr_SW) / &
       9.3892670e-01, 9.3222195e-01, 9.3006462e-01, 9.2740870e-01,  &
       9.2415762e-01, 9.2059308e-01, 9.0948486e-01, 8.2169724e-01,  &
       7.6089543e-01, 7.5043869e-01, 6.5325123e-01, 5.9078658e-01,  &
       6.2885135e-01, 7.0079672e-01, 7.7007401e-01, 7.1458489e-01,  &
       7.8884643e-01, 6.9568723e-01, 6.8699253e-01 /
  
  data (ss_alb_dst(bnd_idx,03),bnd_idx=1,bnd_nbr_SW) / &
       5.4158282e-01, 5.4848081e-01, 5.5060595e-01, 5.5367243e-01,  &
       5.5856991e-01, 5.6502736e-01, 5.8600736e-01, 7.6153868e-01,  &
       8.7799430e-01, 9.0793312e-01, 9.1644675e-01, 9.3001825e-01,  &
       9.4987684e-01, 9.5106703e-01, 8.9816016e-01, 9.6419930e-01,  &
       8.6315483e-01, 9.7507894e-01, 9.6627444e-01 /
  
  data (abs_cff_mss_dst(bnd_idx,03),bnd_idx=1,bnd_nbr_LW) / &
       8.2796326e+01, 1.0993993e+02, 7.7235664e+01, 1.4588206e+02,  &
       2.7262518e+02, 6.9376541e+01 /
  
  data (ext_cff_mss_dst_GSFC_LW(bnd_idx,03),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       3.6145500e+01, 9.6382988e+01, 9.3664528e+01, 1.8338272e+02,  &
       5.0669482e+02, 2.0885854e+02, 9.2025520e+01, 1.7984619e+02,  &
       3.9178537e+02, 1.0425395e+02 /
  
  data (asm_prm_dst_GSFC_LW(bnd_idx,03),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       4.1837148e-02, 1.0239844e-01, 1.6968183e-01, 2.9943594e-01,  &
       3.0478019e-01, 3.8723356e-01, 4.7981682e-01, 5.9323686e-01,  &
       6.7571592e-01, 1.1126740e-01 /
  
  data (ss_alb_dst_GSFC_LW(bnd_idx,03),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       6.2611602e-02, 1.8512115e-01, 2.2346844e-01, 4.1295743e-01,  &
       4.6927378e-01, 2.7643269e-01, 4.0908116e-01, 6.7549521e-01,  &
       9.4383711e-01, 1.3573015e-01 /
  
  ! Data generated by mie on Thu Jun 22 10:28:54 2000
  ! mie version Unknown dated Unknown
  ! Saharan dust aerosol mass extinction/absorption coefficients in m2 kg-1
#if 0
  ! Command line: mie --no_wrn_ntp --dbg=1 --dst_lbl=04 --aer_typ=saharan_dust --dist=lognormal --bnd_nbr=20 --wvl_grd=CCM_SW --bnd_SW_LW=5e-06 --sz_grd=log --sz_mnm=2.5 --sz_mxm=5.0 --sz_nbr=25 --rds_nma=0.2986 --gsd_anl=2.0 /data/zender/dst/mie/aer_saharan_dust_04_CCM_SW.nc
#endif /* not 0 */
  data (ext_cff_mss_dst(bnd_idx,04),bnd_idx=1,bnd_nbr_SW) / &
       1.8521158e+02, 1.8594965e+02, 1.8631862e+02, 1.8665302e+02,  &
       1.8684738e+02, 1.8697920e+02, 1.8789313e+02, 1.9132025e+02,  &
       1.9554166e+02, 1.9782397e+02, 2.0331351e+02, 2.1072499e+02,  &
       2.2536948e+02, 2.0626918e+02, 2.4711586e+02, 3.2010025e+02,  &
       2.2774506e+02, 3.3310596e+02, 3.3746295e+02 /
  
  data (asm_prm_dst(bnd_idx,04),bnd_idx=1,bnd_nbr_SW) / &
       9.4255430e-01, 9.3697166e-01, 9.3490160e-01, 9.3250668e-01,  &
       9.2940676e-01, 9.2540842e-01, 9.1247809e-01, 8.3766031e-01,  &
       8.0380863e-01, 7.9439217e-01, 7.7251023e-01, 7.6373607e-01,  &
       7.4818921e-01, 6.6706318e-01, 7.2609246e-01, 7.4044287e-01,  &
       7.4749053e-01, 7.4257964e-01, 7.4688876e-01 /
  
  data (ss_alb_dst(bnd_idx,04),bnd_idx=1,bnd_nbr_SW) / &
       5.4670489e-01, 5.5145615e-01, 5.5389869e-01, 5.5740213e-01,  &
       5.6180573e-01, 5.6783140e-01, 5.9230453e-01, 7.7780920e-01,  &
       8.6697912e-01, 8.6000067e-01, 8.6635423e-01, 8.8345432e-01,  &
       8.9932209e-01, 8.6735821e-01, 7.9268706e-01, 9.4843066e-01,  &
       7.0466495e-01, 9.6725351e-01, 9.5873028e-01 /
  
  data (abs_cff_mss_dst(bnd_idx,04),bnd_idx=1,bnd_nbr_LW) / &
       1.0874749e+02, 1.2267075e+02, 9.1995964e+01, 1.3173822e+02,  &
       1.5173839e+02, 6.7062096e+01 /
  
  data (ext_cff_mss_dst_GSFC_LW(bnd_idx,04),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       6.4065979e+01, 2.0112622e+02, 1.4719211e+02, 2.4370650e+02,  &
       2.6561081e+02, 1.6597044e+02, 1.2675198e+02, 2.3980673e+02,  &
       3.3320386e+02, 1.4477086e+02 /
  
  data (asm_prm_dst_GSFC_LW(bnd_idx,04),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       1.5509386e-01, 2.4923596e-01, 4.8584163e-01, 6.0789639e-01,  &
       5.9523839e-01, 7.0595628e-01, 7.6246136e-01, 7.8639281e-01,  &
       7.3220348e-01, 3.6878613e-01 /
  
  data (ss_alb_dst_GSFC_LW(bnd_idx,04),bnd_idx=1,bnd_nbr_GSFC_LW) / &
       2.5701949e-01, 4.0907401e-01, 4.4564453e-01, 5.6978035e-01,  &
       4.8119587e-01, 3.7437239e-01, 5.8775944e-01, 7.5951523e-01,  &
       9.2960030e-01, 3.4029695e-01 /
  
#endif /* DST_NBR == 4 */
  
contains
  
  subroutine dst_trn( &
       mpp_dst,             & ! I [kg m-2] Dust path above kth interface level
       dst_trn_ttl)         ! O [frc] Total transmission through all size classes between interfaces k1 and k2
    ! Purpose: Compute dust transmissions needed in absorptivity/emissivity calculations
    ! dst_trn() is called by CCM:physics/radclw() when doabsems is .true.
    use precision ! [mdl] Precision r8, i8, ...
    use pmgrid ! [mdl] Spatial resolution parameters
    implicit none
    ! Parameters
    ! Input
    real(r8),intent(in)::mpp_dst(plond,plevp,dst_nbr) ! I [kg m-2] Dust path above kth interface level
    ! Output
    real(r8),intent(out)::dst_trn_ttl(plond,plevp,plevp,bnd_nbr_LW) ! O [frc] Total transmission through all size classes between interfaces k1 and k2
    ! Local
    integer bnd_idx           ! [idx] LW band index
    integer i                 ! [idx] lon index
    integer k1                ! [idx] lev index
    integer k2                ! [idx] lev index
    integer m                 ! [idx] cst index
    real(r8) dst_pth_dlt          ! [kg m-2] Dust path between interface levels k1 and k2
    real(r8) odap_dst             ! [frc] Path absorption optical depth of this size class
    real(r8) odap_dst_ttl         ! [frc] Total path absorption optical depth of all size classes
    
    do bnd_idx=1,bnd_nbr_LW
       do k1=1,plevp          ! NB: end at plevp
          do k2=1,plevp       ! NB: end at plevp
             do i=1,plon
                odap_dst_ttl=0.0_r8 ! [frc]
                do m=1,dst_nbr
                   dst_pth_dlt=abs(mpp_dst(i,k1,m)-mpp_dst(i,k2,m)) ! [kg m-2] Dust path between interface levels k1 and k2
                   odap_dst=abs_cff_mss_dst(bnd_idx,m)*dst_pth_dlt ! [frc] Absorption optical depth of this size class between interfaces k1 and k2
                   odap_dst_ttl=odap_dst_ttl+odap_dst ! [frc] Total absorption optical depth of all size classes between interfaces k1 and k2
                end do        ! end loop over cst
                ! fxm: Scale aerosol extinction to account for scattering as in CLT99
                dst_trn_ttl(i,k1,k2,bnd_idx)=exp(-1.66*odap_dst_ttl) ! [frc] Total transmission through all size classes between interfaces k1 and k2
             end do           ! end loop over lon
          end do              ! end loop over lev (k2)
       end do                 ! end loop over lev (k1)
    end do                    ! end loop over bnd
    
    return
  end subroutine dst_trn                       ! end dst_trn()
  
end module dstrad
